# Generated by Django 3.2.7 on 2021-09-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_call_number_of_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='number_of_calls',
        ),
    ]
